# Built with Jekyll 3.2.0

# Setup
title:               Muisca Poetry from this millenium
tagline:             'They wanted to erase us from history, but they could not'
description:         'Ed is a Jekyll theme designed for textual editors based on minimal computing principles, and focused on legibility and flexibility.'
url:                 'http://elotroalex.github.io'
baseurl:             '/ed'

# About/contact
author:
  name:              Beatriz Goubert
  url:               https://twitter.com/elotroalex
  email:             beatriz.goubert@gmail.com

# Permalinks

# Color scheme. Options: air, aqua, red, orange, magenta, cyan, blue, light purple

color-scheme: aqua, light purple

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."
